version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "30 7 * * *"
      timezone: "Europe/London"
    target-branch: "main"
    groups:
      github-actions:
        applies-to: "version-updates"
        patterns:
          - "*"
        exclude-patterns:
          - "super-linter/*"
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "uv"
    directories:
      - "/"
    schedule:
      interval: "cron"
      cronjob: "30 7 * * *"
      timezone: "Europe/London"
    target-branch: "main"
    groups:
      uv:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
