name: "Setup Python Dependencies"
description: "Installs Python dependencies"

runs:
  using: "composite"
  steps:
    - name: Set up Just
      uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff # v3.0.0
    - name: Install Python and UV
      uses: astral-sh/setup-uv@803947b9bd8e9f986429fa0c5a41c367cd732b41 # v7.2.1
    - name: Install Python Dependencies
      shell: bash
      run: just install
