name: "Setup Python Dependencies"
description: "Installs Python dependencies"

runs:
  using: "composite"
  steps:
    - name: Set up Just
      uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff # v3.0.0
    - name: Install Python and UV
      uses: astral-sh/setup-uv@1e862dfacbd1d6d858c55d9b792c756523627244 # v7.1.4
    - name: Install Python Dependencies
      shell: bash
      run: just install
