name: "Setup Python Dependencies"
description: "Installs Python dependencies"

runs:
  using: "composite"
  steps:
    - name: Set up Just
      uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4.0.0
    - name: Install Python and UV
      uses: astral-sh/setup-uv@e06108dd0aef18192324c70427afc47652e63a82 # v7.5.0
    - name: Install Python Dependencies
      shell: bash
      run: just install
